# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_transform_pb2 as image__transform__pb2


class EncodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEncode = channel.unary_unary(
                '/flavienbwk.EncodeService/GetEncode',
                request_serializer=image__transform__pb2.sourceImage.SerializeToString,
                response_deserializer=image__transform__pb2.transformedImage.FromString,
                )


class EncodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEncode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEncode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEncode,
                    request_deserializer=image__transform__pb2.sourceImage.FromString,
                    response_serializer=image__transform__pb2.transformedImage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flavienbwk.EncodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EncodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEncode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flavienbwk.EncodeService/GetEncode',
            image__transform__pb2.sourceImage.SerializeToString,
            image__transform__pb2.transformedImage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
